before_script: bundle update
language: ruby
rvm:
  - ruby 2.1.7
script:
  - bundle exec jekyll build
  - bundle exec html-proofer ./_site
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer