before_script: bundle update
language: ruby
rvm:
  - &ruby1 2.3.0
  - &ruby2 2.2.4
  - &ruby3 2.1.8
script:
  - bundle exec jekyll build
  - bundle exec html-proofer ./_site
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer