language: ruby
rvm:
  - 2.1.7
install: gem install -v 1.10.6 bundler --no-rdoc --no-ri
script:
  - bundle _1.10.6_ install
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer