# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Jason's Classroom"
email: jason.kilpatrick@ccd.edu
description: > # this means to ignore newlines until "baseurl:"
  A place to study for your High School Equivalency Diploma
baseurl: "/jekyll" # the subpath of your site, e.g. /blog
url: "http://champa720.github.io" # the base hostname & protocol for your site
permalinks: pretty
twitter_username: champa720
github_username:  champa720

 # Collections

# Build settings
markdown: kramdown
