# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Jason's Classroom"
email: jason.kilpatrick@ccd.edu
description: > # this means to ignore newlines until "baseurl:"
  A place to study for your High School Equivalency Diploma
  
baseurl: "" # the subpath of your site, e.g. /blog
url: http://jekyll.jasonsclassroom.com # the base hostname & protocol for your site
image_path: /assets/img/denver.jpg
random_path: https://unsplash.it/1024/758/?blur

permalinks: pretty

twitter_username: champa720
github_username:  champa720

 # Collections
collections:
  language_arts:
    output: true
    permalink: /resources/language_arts/:path/
  mathematics:
    output: true
    permalink: /resources/mathematics/:path/
  science:
    output: true
    permalink: /resources/science/:path/
  social_studies:
    output: true
    permalink: /resources/social_studies/:path/
  writing:
    output: true
    permalink: /resources/writing/:path/    

# Build settings
markdown: kramdown

 # jekyll-datapage-gen
page_gen:
  - data: 'mathematics-common_core'
    template: 'iframe'
    name: 'title'
    dir: 'resources/mathematics/common_core'
    extension: 'html'